//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgiIslemEnvanter.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depolar
    {
        public int ID { get; set; }
        public string DEPO { get; set; }
        public string URUNTIPI { get; set; }
        public string MARKA { get; set; }
        public string MODEL { get; set; }
        public string SERINO { get; set; }
        public Nullable<bool> SAGLAMMI { get; set; }
        public Nullable<bool> DURUM { get; set; }
    }
}
