//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgiIslemEnvanter.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BilgiIslemEntities : DbContext
    {
        public BilgiIslemEntities()
            : base("name=BilgiIslemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bilgisayarlar> Bilgisayarlar { get; set; }
        public virtual DbSet<Birimler> Birimler { get; set; }
        public virtual DbSet<Depolar> Depolar { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Personeller> Personeller { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tarayicilar> Tarayicilar { get; set; }
        public virtual DbSet<Tasinirlar> Tasinirlar { get; set; }
        public virtual DbSet<TonerCikis> TonerCikis { get; set; }
        public virtual DbSet<TonerGiris> TonerGiris { get; set; }
        public virtual DbSet<TonerStok> TonerStok { get; set; }
        public virtual DbSet<Unvanlar> Unvanlar { get; set; }
        public virtual DbSet<Yazicilar> Yazicilar { get; set; }
        public virtual DbSet<YaziciMarkalari> YaziciMarkalari { get; set; }
        public virtual DbSet<YaziciModelleri> YaziciModelleri { get; set; }
    
        public virtual ObjectResult<tarihfiltresi_Result> tarihfiltresi(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tarihfiltresi_Result>("tarihfiltresi", startParameter, endParameter);
        }
    
        public virtual ObjectResult<TonerCikis> GetFunctionTarihFiltresi(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TonerCikis>("GetFunctionTarihFiltresi", startParameter, endParameter);
        }
    
        public virtual ObjectResult<TonerCikis> GetFunctionTarihFiltresi(Nullable<System.DateTime> start, Nullable<System.DateTime> end, MergeOption mergeOption)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TonerCikis>("GetFunctionTarihFiltresi", mergeOption, startParameter, endParameter);
        }
    }
}
