//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgiIslemEnvanter.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personeller()
        {
            this.Tasinirlar = new HashSet<Tasinirlar>();
            this.Yazicilar = new HashSet<Yazicilar>();
        }
    
        public int ID { get; set; }
        public string SICIL { get; set; }
        public string ADSOYAD { get; set; }
        public Nullable<int> UNVANID { get; set; }
        public Nullable<int> BIRIMID { get; set; }
        public string DAHILITELEFONU { get; set; }
        public string CEPTELEFONU { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual Birimler Birimler { get; set; }
        public virtual Unvanlar Unvanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tasinirlar> Tasinirlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yazicilar> Yazicilar { get; set; }
    }
}
