//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgiIslemEnvanter.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarayicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarayicilar()
        {
            this.Tasinirlar = new HashSet<Tasinirlar>();
        }
    
        public int ID { get; set; }
        public string MARKA { get; set; }
        public string MODEL { get; set; }
        public string SERINO { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public Nullable<bool> ZIMMET { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tasinirlar> Tasinirlar { get; set; }
    }
}
