//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgiIslemEnvanter.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasinirlar
    {
        public int ID { get; set; }
        public Nullable<int> PERSONELID { get; set; }
        public Nullable<int> BILGISAYARID { get; set; }
        public Nullable<int> YAZICIID { get; set; }
        public Nullable<int> TARAYICIID { get; set; }
        public string DOMAINADI { get; set; }
        public string DOMAINIP { get; set; }
        public string YAZICIPORT { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public Nullable<bool> ZIMMET { get; set; }
        public Nullable<bool> BILGIZIMMET { get; set; }
        public Nullable<bool> YAZICIZIMMET { get; set; }
        public Nullable<bool> TARAYICIZIMMET { get; set; }
        public Nullable<int> BIRIMID { get; set; }
    
        public virtual Bilgisayarlar Bilgisayarlar { get; set; }
        public virtual Birimler Birimler { get; set; }
        public virtual Personeller Personeller { get; set; }
        public virtual Tarayicilar Tarayicilar { get; set; }
        public virtual Yazicilar Yazicilar { get; set; }
    }
}
