//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgiIslemEnvanter.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TonerStok
    {
        public int ID { get; set; }
        public Nullable<int> YAZICIMARKALARIID { get; set; }
        public Nullable<int> YAZICIMODELLERIID { get; set; }
        public Nullable<int> TONERGIRISID { get; set; }
        public Nullable<int> TONERCIKISID { get; set; }
        public Nullable<int> KALANTONER { get; set; }
        public Nullable<int> KALANDRUM { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual TonerGiris TonerGiris { get; set; }
        public virtual YaziciMarkalari YaziciMarkalari { get; set; }
        public virtual YaziciModelleri YaziciModelleri { get; set; }
    }
}
