//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgiIslemEnvanter.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yazicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yazicilar()
        {
            this.Tasinirlar = new HashSet<Tasinirlar>();
            this.TonerCikis = new HashSet<TonerCikis>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MARKAID { get; set; }
        public Nullable<int> MODELID { get; set; }
        public string SERINO { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public Nullable<bool> ZIMMET { get; set; }
        public Nullable<int> BIRIMID { get; set; }
        public Nullable<int> PERSONELID { get; set; }
    
        public virtual Birimler Birimler { get; set; }
        public virtual Personeller Personeller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tasinirlar> Tasinirlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TonerCikis> TonerCikis { get; set; }
        public virtual YaziciMarkalari YaziciMarkalari { get; set; }
        public virtual YaziciModelleri YaziciModelleri { get; set; }
    }
}
